sudo: false
language: ruby
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_a7b29cc004b5_key -iv $encrypted_a7b29cc004b5_iv
  -in client_secret.json.enc -out client_secret.json -d
- gem install bundler -v 1.13.6
